# Generated by Django 3.2.9 on 2021-11-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='action',
            field=models.CharField(choices=[('Problem Dismissed', 'Problem Dismissed'), ('Action Taken', 'Action Taken'), ('Problem Settled', 'Problem Settled')], max_length=18, verbose_name='Status'),
        ),
    ]
