# Generated by Django 3.2.9 on 2021-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_alter_complaint_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=18, verbose_name='Type'),
        ),
    ]
