# Generated by Django 3.2.9 on 2021-11-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_rename_is_faculty_user_is_panelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('proof', models.FileField(upload_to='uploaded_files/')),
                ('action', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Campaign', 'Campaign')], max_length=18, verbose_name='Action Type')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
