# Generated by Django 3.2.9 on 2021-11-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_volunteeraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeraction',
            old_name='proof',
            new_name='report',
        ),
    ]
