# Generated by Django 3.2.9 on 2021-11-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_rename_proof_volunteeraction_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaintant',
            new_name='complainant',
        ),
    ]
