# Generated by Django 3.2.9 on 2021-11-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0007_rename_complaintant_complaint_complainant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_complaintant',
            new_name='is_complainant',
        ),
    ]
