# Generated by Django 3.2.9 on 2021-11-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0008_rename_is_complaintant_user_is_complainant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=18, verbose_name='Type'),
        ),
    ]
